package id.ac.univ.regismaba.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import id.ac.univ.regismaba.model.StatistikVerifikatorModel;
import id.ac.univ.regismaba.model.StatistikVerifikatorSummaryModel;

@Mapper
public interface StatistikVerifikatorMapper
{
    @Select("select j.nama_jalur as jenis_rekap, count(*) as jumlah from jalur j, "
            + "mahasiswa m, biodata b where "
            + "m.username=b.username and j.jalur_id=m.jalur_id and b.status_verifikasi = 'Verified'"
            + "j.nama_jalur='SNMPTN' group by j.nama_jalur")
    StatistikVerifikatorModel selectVerifiedSNMPTN();
    
    @Select("select j.nama_jalur as jenis_rekap, count(*) as jumlah from jalur j, "
            + "mahasiswa m, biodata b where "
            + "m.username=b.username and j.jalur_id=m.jalur_id and b.status_verifikasi = 'Verified'"
            + "j.nama_jalur='SBMPTN' group by j.nama_jalur")
    StatistikVerifikatorModel selectVerifiedSBMPTN();
    
    @Select("select j.nama_jalur as jenis_rekap, count(*) as jumlah from jalur j, "
            + "mahasiswa m, biodata b where "
            + "m.username=b.username and j.jalur_id=m.jalur_id and b.status_verifikasi = 'Verified'"
            + "j.nama_jalur='MANDIRI' group by j.nama_jalur")
    StatistikVerifikatorModel selectVerifiedMANDIRI();
    
    @Select("select nama_fakultas as nama, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and j.jalur_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as total, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as regis, "
            + "((select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and j.jalur_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) - "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1)) as non_regis "
            + "from fakultas where fakultas_id=#{fakultas_id}")
    StatistikVerifikatorSummaryModel summaryFacultySNMPTN(@Param("fakultas_id") int fakultas_id);
    
    @Select("select nama_fakultas as nama, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=2 and j.jalur_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as total, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=1 and p.program_id=pr.program_id and pr.program_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as regis, "
            + "((select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=2 and j.jalur_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) - "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=1 and p.program_id=pr.program_id and pr.program_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1)) as non_regis "
            + "from fakultas where fakultas_id=#{fakultas_id}")
    StatistikVerifikatorSummaryModel summaryFacultyPPKB(@Param("fakultas_id") int fakultas_id);
    
    @Select("select nama_fakultas as nama, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=3 and j.jalur_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as total, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=1 and p.program_id=pr.program_id and pr.program_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as regis, "
            + "((select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=3 and j.jalur_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) - "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=1 and p.program_id=pr.program_id and pr.program_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1)) as non_regis "
            + "from fakultas where fakultas_id=#{fakultas_id}")
    StatistikVerifikatorSummaryModel summaryFacultyTalent(@Param("fakultas_id") int fakultas_id);
    
    @Select("select nama_fakultas as nama, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and j.jalur_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as total, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as regis, "
            + "((select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and j.jalur_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) - "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id "
            + "and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1)) as non_regis "
            + "from fakultas where fakultas_id=#{fakultas_id}")
    StatistikVerifikatorSummaryModel summaryFacultySBMPTN(@Param("fakultas_id") int fakultas_id);
    
    @Select("select nama_fakultas as nama, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=1 and j.jalur_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as total, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=2 and p.program_id=pr.program_id and pr.program_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as regis, "
            + "((select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=1 and j.jalur_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) - "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=2 and p.program_id=pr.program_id and pr.program_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1)) as non_regis "
            + "from fakultas where fakultas_id=#{fakultas_id}")
    StatistikVerifikatorSummaryModel summaryFacultySBMPTNReg(@Param("fakultas_id") int fakultas_id);
    
    @Select("select nama_fakultas as nama, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=2 and j.jalur_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as total, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=2 and p.program_id=pr.program_id and pr.program_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as regis, "
            + "((select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=2 and j.jalur_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) - "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=2 and p.program_id=pr.program_id and pr.program_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1)) as non_regis "
            + "from fakultas where fakultas_id=#{fakultas_id}")
    StatistikVerifikatorSummaryModel summaryFacultySBMPTNPar(@Param("fakultas_id") int fakultas_id);
    
    @Select("select nama_fakultas as nama, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and j.jalur_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as total, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as regis, "
            + "((select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and j.jalur_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) - "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1)) as non_regis "
            + "from fakultas where fakultas_id=#{fakultas_id}")
    StatistikVerifikatorSummaryModel summaryFacultyMANDIRI(@Param("fakultas_id") int fakultas_id);
    
    @Select("select nama_fakultas as nama, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=1 and j.jalur_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as total, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=3 and p.program_id=pr.program_id and pr.program_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as regis, "
            + "((select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=1 and j.jalur_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) - "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=3 and p.program_id=pr.program_id and pr.program_id=1 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1)) as non_regis "
            + "from fakultas where fakultas_id=#{fakultas_id}")
    StatistikVerifikatorSummaryModel summaryFacultyMANDIRIReg(@Param("fakultas_id") int fakultas_id);
    
    @Select("select nama_fakultas as nama, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=2 and j.jalur_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as total, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=3 and p.program_id=pr.program_id and pr.program_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as regis, "
            + "((select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=2 and j.jalur_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) - "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=3 and p.program_id=pr.program_id and pr.program_id=2 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1)) as non_regis "
            + "from fakultas where fakultas_id=#{fakultas_id}")
    StatistikVerifikatorSummaryModel summaryFacultyMANDIRIPar(@Param("fakultas_id") int fakultas_id);
    
    @Select("select nama_fakultas as nama, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=3 and j.jalur_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as total, "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=3 and p.program_id=pr.program_id and pr.program_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) as regis, "
            + "((select count(*) from mahasiswa m, program_studi p, fakultas f, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.jalur_id=j.jalur_id and f.fakultas_id=#{fakultas_id} and p.program_id=pr.program_id and pr.program_id=3 and j.jalur_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1) - "
            + "(select count(*) from mahasiswa m, program_studi p, fakultas f, biodata b, jalur j, program pr, tahun_ajaran t, jenjang jn where m.program_studi_id=p.program_studi_id and p.fakultas_id=f.fakultas_id and m.username=b.username and b.status_verifikasi = 'Verified' and f.fakultas_id=#{fakultas_id} and m.jalur_id=j.jalur_id and j.jalur_id=3 and p.program_id=pr.program_id and pr.program_id=3 and m.tahun_ajaran_id=t.tahun_ajaran_id and t.tahun_ajaran_id=4 and p.jenjang_id=jn.jenjang_id and jn.jenjang_id=1)) as non_regis "
            + "from fakultas where fakultas_id=#{fakultas_id}")
    StatistikVerifikatorSummaryModel summaryFacultyMANDIRIKKI(@Param("fakultas_id") int fakultas_id);
}
